on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
  schedule:
  # random HH:MM to avoid a load spike on GitHub Actions at 00:00
  - cron: 48 1 * * *
  
name: Semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep

    # Skip any PR created by dependabot to avoid permission issues:
    if: (github.actor != 'dependabot[bot]')

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up JDK 23
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '23'
          cache: 'maven' 
          check-latest: true

      - name: Install Maven
        run: |
          apt-get update
          apt-get install -y maven

      - name: Semgrep Security Scan
        run: |
          semgrep ci --allow-local-builds
